# configuração de container - docker
# criação do container com imagem do db (conexão feita com o mysql)

# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db1:/var/lib/mysql

volumes:
  db1: